{
 "title": "MyElectricalData - Enedis",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "price_STD", "label": "€ / kWh Base", "query": "0.2162" },
   { "name": "price_HC", "label": "€ / kWh (HC)", "query": "0,1736" },
   { "name": "price_HP", "label": "€ / kWh (HP)", "query": "0,2338" },
   { "name": "surface_maison", "label": "Surface de la maison", "query": "120" },
   { "name": "facteur_energie", "label": "Facteur énergie primaire", "query": "2.3" }
  ]
 },
 "panels": [
  {
   "title": "Conso. HP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"myelectricaldata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\r\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\r\n  |> sum(column: \"_value\")\r\n  |> group()\r\n  |> yield()\r\n"
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\" or r[\"measure_type\"] == \"HP\")\n  |> group(columns: [\"measure_type\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    }
   ]
  },
  {
   "title": "Puissance consommée - en kW - 7 derniers jours",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  \n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HC\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  \n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HP\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "Temp. Ext.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "℃",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temperature_exterieur_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "temperature_exterieur_temperature"
      }
     ]
    },
    {
     "alias": "Temp. Ext.",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"sensor.temp_exterieure_moyenne\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    }
   ]
  },
  {
   "title": "Classe Energetique",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "$A/1000/$surface_maison*$facteur_energie",
     "type": "math"
    }
   ]
  },
  {
   "title": "Conso. HC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"myelectricaldata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\r\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\r\n  |> sum(column: \"_value\")\r\n  |> group()\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Conso. Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"myelectricaldata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\r\n  |> sum(column: \"_value\")\r\n  |> group()\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"math\"\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: -12mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> group(columns: [\"_field\"])\n  |> sum(column: \"_value\")\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "expression": "$A/1000/$surface_maison*$facteur_energie",
     "type": "math"
    }
   ]
  },
  {
   "title": "Consommation mensuelle année en cours",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 9 }
  },
  {
   "title": "Consommation mensuelle année n-1",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 9 }
  },
  {
   "title": "Consommation mensuelle année n-2",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 9 }
  },
  {
   "title": "Consommation mensuelle année n-3",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 9 }
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1d))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Prix base (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1d))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Prix base (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -2y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Prix base (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -2y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -3y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Prix base (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -3y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1d))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -1y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -2y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "import \"date\"\nyear_to_study = string(v: date.year(t: -3y))\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == year_to_study)\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "title": "Puissance consommée - en kW - 12 derniers mois",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "(k)W",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group() ",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Energie consommée par jour - en kWh - 12 derniers mois",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "kWh/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "consumption_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Total\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> timeShift(duration: -1d)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HC\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> timeShift(duration: -1d)\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HP\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temperature_exterieur_temperature\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temp_interieure_moyenne\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Int.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    }
   ]
  }
 ]
}