{
 "title": "MyElectricalData - Linky Data",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "pdl", "label": "Point de livraison", "query": "MY_PDL" },
   { "name": "price_STD", "label": "€ / kWh Base", "query": "0.1658" },
   { "name": "price_HC", "label": "€ / kWh (HC)", "query": "0,1401" },
   { "name": "price_HP", "label": "€ / kWh (HP)", "query": "0,1754" },
   { "name": "surface_maison", "label": "Surface de la maison", "query": "120" }
  ]
 },
 "panels": [
  {
   "title": "Consommation Heures Pleines",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\" or r[\"measure_type\"] == \"HP\")\n  |> group(columns: [\"measure_type\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    }
   ]
  },
  {
   "title": "Heures Pleines ($price_HP€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    }
   ]
  },
  {
   "title": "Base vs HC/HP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(($A/$B)-1)", "type": "math" }
   ]
  },
  {
   "title": "Classe Energetique",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$A/1000/120", "type": "math" }
   ]
  },
  {
   "title": "Consommation Heures Creuses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Heures Creuses ($price_HC€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Tarif Base ($price_STD€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> group(columns: [\"_field\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()\n",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Période Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Tarif HC/HP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\" or r[\"measure_type\"] == \"HP\")\n  |> group(columns: [\"_field\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()\n",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "import \"math\"\nfrom(bucket: \"myelectricaldata\")\n  |> range(start: -12mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> group(columns: [\"_field\"])\n  |> sum(column: \"_value\")\n  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    },
    { "expression": "$A/1000/120", "type": "math" }
   ]
  },
  {
   "title": "Power Consumption - in (k)W",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  \n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HC\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  \n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HP\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"sum\")",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "Temp. Ext.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "℃",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temperature_exterieur_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n       \nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\n\nNamedSeries  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "temperature_exterieur_temperature"
      }
     ]
    },
    {
     "alias": "Temp. Ext.",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temperature_exterieur_temperature\")\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    }
   ]
  },
  {
   "title": "Energy Consumption - per Day (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Watt/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: -30d, stop: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Watts/day\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()\n",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  { "title": "2023", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 18 } },
  { "title": "2022", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 18 } },
  { "title": "2021", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 18 } },
  { "title": "2020", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 18 } },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2023\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == \"2023\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2022\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == \"2022\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2021\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == \"2021\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2020\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "enedisgateway_daily",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"year\"] == \"2020\")\n  |> group(columns: [\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2023",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2023\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2022",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2022\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2021",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2021\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2020",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: 1990-01-01T00:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> filter(fn: (r) => r[\"year\"] == \"2020\")\n  |> group(columns: [\"month\",\"year\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield()",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B -1", "type": "math" }
   ]
  },
  {
   "title": "Power Consumption - in (k)W",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "(k)W",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group() ",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Energy Consumption - per Day (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "kWh/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "enedisgateway_detail",
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Total\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pdl", "operator": "=~", "value": "/^$pdl$/" }
     ]
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HC\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"myelectricaldata\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption_detail\")\n  |> filter(fn: (r) => r[\"measure_type\"] == \"HP\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wh\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"HP\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries  |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temperature_exterieur_temperature\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Ext.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nRawSeries = from(bucket: \"home_assistant_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"℃\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"entity_id\"] == \"temp_interieure_moyenne\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\nNamedSeries = RawSeries\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Temp. Int.\"}))\n  |> keep(columns:FinalOutput)\nNamedSeries |> yield()"
    }
   ]
  }
 ]
}